changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Fixes ✨
      labels:
        - bugfix
    - title: Code Cleanup 🪥
      labels:
        - cleanup
    - title: Other Changes
      labels:
        - "*"